.TH fail2rest 1 "" "" "General Commands Manual"
.SH NAME
fail2rest \- REST server for fail2ban
.SH SYNOPSIS
fail2rest [options]
.SH DESCRIPTION
fail2rest is a small REST server that aims to allow full administration of a fail2ban(1) server via HTTP
.SH OPTIONS
\-config
specify path to json configuration for fail2rest.
.TP
\-h
prints available arguments, then exits.
.SH SEE ALSO
fail2ban(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Sean DuBois (sean@siobud.com)
